# Generated by Django 5.1.2 on 2024-11-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('review_author', 'Can review Author')]},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('review_book', 'Can review a book')]},
        ),
    ]
