# Generated by Django 5.1.2 on 2024-11-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_author_options_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('review_book', 'Can review a book'), ('can_view', 'Can view books'), ('can_edit', 'Can edit a book'), ('can_create', 'Can create a new book'), ('can_delete', 'Can delete a book')]},
        ),
    ]
